/*
 * Acceso a Datos - Proyecto final
 */
package entrenamientos.visual;

import entrenamientos.AccesoDatosExist;
import entrenamientos.AccesoDatosSql;
import entrenamientos.objetos.Cliente;
import entrenamientos.objetos.Ejercicios;
import entrenamientos.objetos.Rutinas;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gianfranco Álvarez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * 
     */
    public Ventana() {
        initComponents();
        limpar();
        jPanelDatosUsuario.setVisible(false);
        jButtonAddRutina.setVisible(false);
        jButtonAddEjer.setVisible(false);
        jButtonAddOtroEjer.setVisible(false);
        //Abrimos una única conexión para toda la ejecución
        AccesoDatosExist.abrirConexion();
        //Inicializamos los desplegables de nombres apellidos con los datos de la base de datos
        actualizarComboNombres();
        actualizarComboApel(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelCabecera = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        btDatosCliente = new javax.swing.JButton();
        comboNombre = new javax.swing.JComboBox<>();
        comboApel1 = new javax.swing.JComboBox<>();
        jButtonLimpiar = new javax.swing.JButton();
        btRutinas = new javax.swing.JButton();
        jPanelDatosUsuario = new javax.swing.JPanel();
        jLabeldatosCliente = new javax.swing.JLabel();
        jLabelNombredatos = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jScrollPanerRutinas = new javax.swing.JScrollPane();
        tablaRutinas = new javax.swing.JTable();
        jButtonAddRutina = new javax.swing.JButton();
        jScrollPaneEjercicios = new javax.swing.JScrollPane();
        tablaEjercicios = new javax.swing.JTable();
        jButtonAddEjer = new javax.swing.JButton();
        jButtonAddOtroEjer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jlabelCabecera.setBackground(new java.awt.Color(0, 255, 204));
        jlabelCabecera.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlabelCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelCabecera.setText("Planes de entrenamiento");

        jLabelCliente.setText("Nombre");

        btDatosCliente.setText("Info cliente");
        btDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDatosClienteActionPerformed(evt);
            }
        });

        comboNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombreActionPerformed(evt);
            }
        });

        comboApel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboApel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboApel1ActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        btRutinas.setText("Cargar rutinas");
        btRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRutinasActionPerformed(evt);
            }
        });

        jPanelDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabeldatosCliente.setText("Nª cliente:");

        jLabelNombredatos.setText("Nombre:");

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jLabelTelefono.setText("Teléfono:");

        jLabelEmail.setText("Email:");

        javax.swing.GroupLayout jPanelDatosUsuarioLayout = new javax.swing.GroupLayout(jPanelDatosUsuario);
        jPanelDatosUsuario.setLayout(jPanelDatosUsuarioLayout);
        jPanelDatosUsuarioLayout.setHorizontalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabeldatosCliente)
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldId))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelTelefono)
                            .addComponent(jLabelNombredatos))
                        .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEmail)))
                            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanelDatosUsuarioLayout.setVerticalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeldatosCliente)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombredatos)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tablaRutinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Frecuencia"
            }
        ));
        tablaRutinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRutinasMouseClicked(evt);
            }
        });
        jScrollPanerRutinas.setViewportView(tablaRutinas);

        jButtonAddRutina.setText("Añadir rutina");
        jButtonAddRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRutinaActionPerformed(evt);
            }
        });

        tablaEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Series", "Repeticiones", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEjercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEjerciciosMouseClicked(evt);
            }
        });
        jScrollPaneEjercicios.setViewportView(tablaEjercicios);

        jButtonAddEjer.setText("Añadir ejercicio");
        jButtonAddEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEjerActionPerformed(evt);
            }
        });

        jButtonAddOtroEjer.setText("Añadir otro ejercicio");
        jButtonAddOtroEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOtroEjerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPanerRutinas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboApel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLimpiar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(btDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btRutinas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPaneEjercicios))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddRutina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddEjer))
                            .addComponent(jButtonAddOtroEjer))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlabelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(comboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboApel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDatosCliente)
                    .addComponent(btRutinas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanerRutinas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddRutina)
                    .addComponent(jButtonAddEjer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddOtroEjer)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Cerramos la conexión cuando se cierra la aplicación
        AccesoDatosExist.cerrarConexion();

    }//GEN-LAST:event_formWindowClosed

    //Si se selecciona el no0mbre 
    private void comboNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNombreActionPerformed
        String nombreSelect = (String) comboNombre.getSelectedItem();
        actualizarComboApel(nombreSelect);
    }//GEN-LAST:event_comboNombreActionPerformed

    //Botón ver datos cliente
    private void btDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDatosClienteActionPerformed

        actualizarInfoClientes();


    }//GEN-LAST:event_btDatosClienteActionPerformed

    private void comboApel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboApel1ActionPerformed
        // TODO add your handling code here:
        String nombreSelect = (String) comboNombre.getSelectedItem();
        String apelSelect = (String) comboApel1.getSelectedItem();;

        if (!apelSelect.equals("TODOS")) {
            nombreSelect = AccesoDatosExist.buscarNombreUnico(apelSelect);
        }
        comboNombre.setSelectedItem(nombreSelect);
        comboApel1.setSelectedItem(apelSelect);

    }//GEN-LAST:event_comboApel1ActionPerformed
    //boton clear
    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed
    //Boton cargar rutinas
    private void btRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRutinasActionPerformed
        // TODO add your handling code here:

        if (!comboNombre.getSelectedItem().toString().equals("TODOS")) {
            if (!comboApel1.getSelectedItem().toString().equals("TODOS")) {
                idCliente = AccesoDatosExist.buscarIdCliente(comboNombre.getSelectedItem().toString(), comboApel1.getSelectedItem().toString());
                actualizarTablaRutinas(idCliente);
                actualizarInfoClientes();
                tablaEjercicios.removeAll();
                tablaEjercicios.setModel(new DefaultTableModel());
                jButtonAddRutina.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Hay que seleccionar apellido", "", JOptionPane.ERROR_MESSAGE);
                limpar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hay que seleccionar nombre ", "", JOptionPane.ERROR_MESSAGE);
            limpar();
        }


    }//GEN-LAST:event_btRutinasActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void tablaEjerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEjerciciosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaEjerciciosMouseClicked

    private void tablaRutinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRutinasMouseClicked
        // TODO add your handling code here:
        int fila = tablaRutinas.getSelectedRow();
        actualizarTablaEjericios(tablaRutinas.getModel().getValueAt(fila, 0).toString());
    }//GEN-LAST:event_tablaRutinasMouseClicked
    //añadir rutina
    private void jButtonAddRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRutinaActionPerformed
        // TODO add your handling code here:
        //ABRIR VENTANA  Y RECOGER DATOS
        AddRutina ventanaCrear = new AddRutina(this, idCliente);
        ventanaCrear.setVisible(rootPaneCheckingEnabled);
        ventanaCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAddRutinaActionPerformed

    private void jButtonAddEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEjerActionPerformed
        // TODO add your handling code here:
        //ABRIR VENTANA  Y RECOGER DATOS
        AddEjercicio ventanaCrear = new AddEjercicio(this, tablaRutinas.getModel().getValueAt(tablaRutinas.getSelectedRow(), 0).toString());
        ventanaCrear.setVisible(rootPaneCheckingEnabled);
        ventanaCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAddEjerActionPerformed

    private void jButtonAddOtroEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOtroEjerActionPerformed
        // TODO add your handling code here:
        //ABRIR VENTANA  Y RECOGER DATOS
        AddEjercicio ventanaCrear = new AddEjercicio(this, tablaRutinas.getModel().getValueAt(tablaRutinas.getSelectedRow(), 0).toString());
        ventanaCrear.setVisible(rootPaneCheckingEnabled);
        ventanaCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAddOtroEjerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDatosCliente;
    private javax.swing.JButton btRutinas;
    private javax.swing.JComboBox<String> comboApel1;
    private javax.swing.JComboBox<String> comboNombre;
    private javax.swing.JButton jButtonAddEjer;
    private javax.swing.JButton jButtonAddOtroEjer;
    private javax.swing.JButton jButtonAddRutina;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNombredatos;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabeldatosCliente;
    private javax.swing.JPanel jPanelDatosUsuario;
    private javax.swing.JScrollPane jScrollPaneEjercicios;
    private javax.swing.JScrollPane jScrollPanerRutinas;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JLabel jlabelCabecera;
    private javax.swing.JTable tablaEjercicios;
    private javax.swing.JTable tablaRutinas;
    // End of variables declaration//GEN-END:variables
    private String idCliente = "";

    private void actualizarComboNombres() {
        //Buscamos la lista completa de nombres
        ArrayList<String> nombres = AccesoDatosExist.buscarNombre();
        //Añadimos la opción "TODAS" al comienzo de la lista
        nombres.add(0, "TODOS");
        comboNombre.setModel(new javax.swing.DefaultComboBoxModel<>(nombres.toArray(new String[0])));
    }

    private void actualizarComboApel(String nombre) {
        //Buscamos la lista de apellidos 
        ArrayList<String> apels = AccesoDatosExist.buscarApels(nombre);
        //Añadimos la opción "TODOS" al comienzo de la lista
        apels.add(0, "TODOS");
        comboApel1.setModel(new javax.swing.DefaultComboBoxModel<>(apels.toArray(new String[0])));
    }

    private void limpar() {
        actualizarComboNombres();
        actualizarComboApel(null);
        jPanelDatosUsuario.setVisible(false);
        jButtonAddRutina.setVisible(false);
        jButtonAddEjer.setVisible(false);
        jButtonAddOtroEjer.setVisible(false);
        tablaRutinas.removeAll();
        tablaRutinas.setModel(new DefaultTableModel());
        tablaEjercicios.removeAll();
        tablaEjercicios.setModel(new DefaultTableModel());
        idCliente = "";
    }

    public void actualizarTablaRutinas(String codCliente) {

        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Código");
        tableHeaders.add("Frecuencia");

        ArrayList<Rutinas> rutinas = AccesoDatosSql.buscarRutinas(codCliente);

        for (Rutinas rutina : rutinas) {
            Vector<Object> oneRow = new Vector<Object>();

            oneRow.add(rutina.getCodRutina());
            oneRow.add(rutina.getFrecuenciaSemana());
            tableData.add(oneRow);
        }

        tablaRutinas.setModel(new DefaultTableModel(tableData, tableHeaders));

    }

    public void actualizarTablaEjericios(String codRutina) {

        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Nombre");
        tableHeaders.add("Grupo Muscular");
        tableHeaders.add("Series");
        tableHeaders.add("Repeticiones");
        tableHeaders.add("Peso");

        ArrayList<Ejercicios> ejercicios = AccesoDatosSql.buscarEjercicios(codRutina);
        
        if (ejercicios.size() != 0) {
            
            for (Ejercicios ejercicio : ejercicios) {
                Vector<Object> oneRow = new Vector<Object>();

                oneRow.add(ejercicio.getNombre());
                oneRow.add(ejercicio.getGrupoMuscular());
                oneRow.add(ejercicio.getSeries());
                oneRow.add(ejercicio.getRepeticiones());
                oneRow.add(ejercicio.getPeso());
                tableData.add(oneRow);
            }
            tablaEjercicios.setModel(new DefaultTableModel(tableData, tableHeaders));
            jButtonAddEjer.setVisible(false);
            jButtonAddOtroEjer.setVisible(true);
        }
        else
        {
            tablaEjercicios.removeAll();
            tablaEjercicios.setModel(new DefaultTableModel());
            jButtonAddEjer.setVisible(true);
            jButtonAddOtroEjer.setVisible(false);
        }

    }

    private void actualizarInfoClientes() {
        Cliente cliente = AccesoDatosExist.buscarInfoCliente(comboNombre.getSelectedItem().toString(), comboApel1.getSelectedItem().toString());
        if (cliente != null) {
            jPanelDatosUsuario.setVisible(true);
            jTextFieldId.setEditable(false);
            jTextFieldNombre.setEditable(false);
            jTextFieldApellidos.setEditable(false);
            jTextFieldTelefono.setEditable(false);
            jTextFieldEmail.setEditable(false);

            jTextFieldId.setText(cliente.getId());
            jTextFieldNombre.setText(cliente.getNombre());
            jTextFieldApellidos.setText(cliente.getApel1() + " " + cliente.getApel2());
            jTextFieldTelefono.setText(cliente.getTelefono());
            jTextFieldEmail.setText(cliente.getCorreo());
        } else {
            JOptionPane.showMessageDialog(null, "Hay que seleccionar tanto nombre como apellido", "", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }
}
