DROP DATABASE IF EXISTS ENTRENAMIENTO;
CREATE DATABASE ENTRENAMIENTO;
USE ENTRENAMIENTO;


CREATE TABLE RUTINAS
( COD_RUTINA VARCHAR(10) PRIMARY KEY,
  ID_CLIENTE VARCHAR(10),
  FRECUENCIA_SEMANA INTEGER
);


CREATE  TABLE EJERCICIOS
(
  NOMBRE  VARCHAR(30),
  COD_RUTINA VARCHAR(10),
  GRUPO_MUSCULAR ENUM('TS', 'TI'), -- 'TS': TREN SUPERIOR, 'TI': TREN INFERIOR
  SERIES INTEGER,
  REPETICIONES INTEGER,
  PESO_ADD INTEGER,
  CONSTRAINT PK_EJERCICIOS PRIMARY KEY(COD_RUTINA, NOMBRE),
  CONSTRAINT FK_EJERCICIOS FOREIGN KEY(COD_RUTINA) REFERENCES RUTINAS(COD_RUTINA),
  CONSTRAINT UK_EJERCICIOS UNIQUE(COD_RUTINA, NOMBRE)
);


INSERT INTO RUTINAS VALUES('R1','1',3);
INSERT INTO RUTINAS VALUES('R2','1',3);
INSERT INTO RUTINAS VALUES('R3','2',3);
INSERT INTO RUTINAS VALUES('R4','3',3);
INSERT INTO RUTINAS VALUES('R5','4',3);


INSERT INTO EJERCICIOS VALUES('Dominada prona','R1','TS',3,10,0);
INSERT INTO EJERCICIOS VALUES('Dominada neutra','R1','TS',3,10,0);
INSERT INTO EJERCICIOS VALUES('Dominada supiona','R1','TS',3,10,0);
INSERT INTO EJERCICIOS VALUES('Mancuernas','R1','TS',3,10,18);

INSERT INTO EJERCICIOS VALUES('Dominada prona','R2','TS',3,4,40);
INSERT INTO EJERCICIOS VALUES('Dominada neutra','R2','TS',3,4,40);
INSERT INTO EJERCICIOS VALUES('Dominada supiona','R2','TS',3,4,40);
INSERT INTO EJERCICIOS VALUES('Mancuernas','R2','TS',3,10,16);

INSERT INTO EJERCICIOS VALUES('Sentadilla','R3','TI',3,10,90);
INSERT INTO EJERCICIOS VALUES('Peso muerto','R3','TI',3,10,140);
INSERT INTO EJERCICIOS VALUES('Zancadas','R3','TI',3,10,40);
INSERT INTO EJERCICIOS VALUES('Elvaciones gemelo','R3','TI',3,10,16);



Commit;

