/*
 * Acceso a Datos - Tarea UT3
 */
package com.mycompany.ad03_conectores;


import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alba
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("CODIGO");
        tableHeaders.add("FECHA");
        tableHeaders.add("ORIGEN");
        tableHeaders.add("DESTINO");
        ArrayList<Vuelo> vuelos = AccesoDatos.buscarVuelos();
        for (Vuelo vuelo : vuelos) {
            Vector<Object> oneRow = new Vector<Object>();
            
            oneRow.add(vuelo.getCodigo_vuelo());
            oneRow.add(vuelo.getFecha_hora());
            oneRow.add(vuelo.getOrigen());
            oneRow.add(vuelo.getDestino());
            
            //FIN
            tableData.add(oneRow);
        }
        
        tablaVuelos.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPasajeros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nuevoPasajero = new javax.swing.JButton();
        eliiminarPasajero = new javax.swing.JButton();
        cambiarAsiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "TIPO", "NUMERO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPasajeros);
        if (tablaPasajeros.getColumnModel().getColumnCount() > 0) {
            tablaPasajeros.getColumnModel().getColumn(0).setResizable(false);
            tablaPasajeros.getColumnModel().getColumn(1).setResizable(false);
            tablaPasajeros.getColumnModel().getColumn(2).setResizable(false);
        }

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "FECHA", "ORIGEN", "DESTINO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVuelosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVuelos);
        if (tablaVuelos.getColumnModel().getColumnCount() > 0) {
            tablaVuelos.getColumnModel().getColumn(0).setResizable(false);
            tablaVuelos.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("VUELOS");

        jLabel2.setText("PASAJEROS");

        nuevoPasajero.setText("AÑADIR PASAJERO");
        nuevoPasajero.setActionCommand("nuevoPasajero");
        nuevoPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPasajeroActionPerformed(evt);
            }
        });

        eliiminarPasajero.setText("ELIMINAR PASAJERO");
        eliiminarPasajero.setActionCommand("eliminarPasajero");
        eliiminarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliiminarPasajeroActionPerformed(evt);
            }
        });

        cambiarAsiento.setText("CAMBIAR ASIENTO");
        cambiarAsiento.setActionCommand("cambiarAsiento");
        cambiarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarAsientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoPasajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliiminarPasajero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(cambiarAsiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nuevoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cambiarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(eliiminarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPasajeroActionPerformed
        int fila = tablaVuelos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un vuelo para añadir un pasajero.");
        } else {
            //ABRIR VENTANA  Y RECOGER DATOS
            VentanaPasajero ventanaCrear = new VentanaPasajero(this, VentanaPasajero.MODO_CREAR);
            ventanaCrear.setVisible(rootPaneCheckingEnabled);
            ventanaCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);   
       }
    }//GEN-LAST:event_nuevoPasajeroActionPerformed

    private void eliiminarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliiminarPasajeroActionPerformed
        int fila = tablaPasajeros.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un pasajero para eliminar.");
        } else {
            String dniPasajero = tablaPasajeros.getModel().getValueAt(fila, 0).toString();
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar el pasajero con dni " + dniPasajero + "?");
            if (confirmacion == 0) {
                String mensaje = AccesoDatos.borrarPasajero(codigoVuelo, dniPasajero);
                JOptionPane.showMessageDialog(null, mensaje);
                   
                actualizarTablaPasajeros();
            }
        }
    }//GEN-LAST:event_eliiminarPasajeroActionPerformed

    private void cambiarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarAsientoActionPerformed
        int fila = tablaPasajeros.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un pasajero para cambiar el asiento.");
        } else {
            //ABRIR VENTANA  Y RECOGER DATOS
            VentanaPasajero ventanaEditar = new VentanaPasajero(this, VentanaPasajero.MODO_EDITAR);
            ventanaEditar.setCampoDNI(tablaPasajeros.getModel().getValueAt(fila, 0).toString());
            ventanaEditar.setCampoTipoPlaza(tablaPasajeros.getModel().getValueAt(fila, 1).toString());
            ventanaEditar.setCampoAsiento(tablaPasajeros.getModel().getValueAt(fila, 2).toString());
            ventanaEditar.setVisible(rootPaneCheckingEnabled);
            ventanaEditar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);   
            
        }
    }//GEN-LAST:event_cambiarAsientoActionPerformed

    private void tablaVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVuelosMouseClicked
        int fila = tablaVuelos.getSelectedRow();
        codigoVuelo = tablaVuelos.getModel().getValueAt(fila, 0).toString();
        actualizarTablaPasajeros();
    }//GEN-LAST:event_tablaVuelosMouseClicked

    
    public void actualizarTablaPasajeros() {
         
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("DNI");
        tableHeaders.add("TIPO");
        tableHeaders.add("PLAZA");
        
        ArrayList<Pasajero> pasajeros = AccesoDatos.buscarPasajeros(codigoVuelo);
        
        for (Pasajero pasajero : pasajeros) {
            Vector<Object> oneRow = new Vector<Object>();
            
            oneRow.add(pasajero.getDni());
            oneRow.add(pasajero.getTipo_plaza());
            oneRow.add(pasajero.getPlaza());
            
            tableData.add(oneRow);
        }
        
        tablaPasajeros.setModel(new DefaultTableModel(tableData, tableHeaders));
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarAsiento;
    private javax.swing.JButton eliiminarPasajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nuevoPasajero;
    private javax.swing.JTable tablaPasajeros;
    private javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables

    private String codigoVuelo;

    public String getCodigoVuelo() {
        return codigoVuelo;
    }

}
